const products = [

{
  id: 1,
  name: "👗 Kurtis",
  category: "Women's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim1.flixcart.com/image/2048/2048/xif0q/kurta/r/r/i/m-sarasa-220y-sa-rasa-resized-original-imah8dsthexhbp6z.jpeg?q=90",
  link: "https://fktr.in/U5B3nB6"
},
{
  id: 2,
  name: "🥻 Sarees",
  category: "Women's Fashion",
  price: 264,
  oldPrice: 999,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/l2nmnww0/sari/s/a/3/free-lv-214-leelavati-unstitched-original-imagdy7ahvdbpnj9.jpeg?q=70",
  link: "https://fktr.in/lA6IrfI"
},
{
id:3,
name:"👚 Tops & T-Shirts",
category:"Women's Fashion",
price:499,
oldPrice:999,
discount:"50% OFF",
rating:4.4,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/g/m/l/s-dl-womenstop146-tanushk-original-imahzgzzzhcxzvgf.jpeg?q=70",
link:"https://fktr.in/PFpyf68"
},
{
id:4,
name:"👖 Jeans & Trousers",
category:"Women's Fashion",
price:149,
oldPrice:999,
discount:"60% OFF",
rating:4.6,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/kzd147k0/trouser/s/t/m/30-denim-moti-light-blue-button-stylokat-original-imagbdxfxegfgxnz.jpeg?q=70",
link:"https://fktr.in/fuFgWju"
},
{
id:5,
name:"👗 Western Dresses",
category:"Women's Fashion",
price:199 - 2999,
oldPrice:1999,
discount:"55% OFF",
rating:4.4,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/dress/z/8/c/xl-red-dress-aarti-fashion-original-imahgzhggxagyx5z.jpeg?q=70",
link:"https://fktr.in/rsr90mg"
},
{
id:6,
name:"👘 Lehenga & Gowns",
category:"Women's Fashion",
price:199,
oldPrice:1199,
discount:"50% OFF",
rating:4.2,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/gown/c/2/h/no-m-full-sleeve-stitched-dvd-pink-gown-2-reva-enterprise-no-original-imah2w2mfwzuzrhg.jpeg?q=70",
link:"https://fktr.in/lUWyqgN"
},
{
id:7,
name:"🩳 Co-ord Sets",
category:"Women's Fashion",
price:199,
oldPrice:1599,
discount:"50% OFF",
rating:4.3,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/apparel-set/i/g/j/s-oly-coardset-70-co-ords-olywear-original-imahh73vm6jqvrnd.jpeg?q=70",
link:"https://fktr.in/7wCUzna"
},
{
id:8,
name:"🧥 Ethnic Sets",
category:"Women's Fashion",
price:199,
oldPrice:2499,
discount:"40% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/ethnic-set/j/q/d/xxl-ac-1102-yusra-original-imagqzyhufzhtqkn.jpeg?q=70",
link:"https://fktr.in/7xIHENa"
},
{
id:9,
name:"👜 Handbags",
category:"Women's Fashion",
price:599,
oldPrice:799,
discount:"25% OFF",
rating:4.4,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-hand-messenger-bag/q/u/0/woman-purse-purse-woman-bag-purse-women-style-hand-held-bag-original-imahjky2jjgfa7xa.jpeg?q=70",
link:"https://fktr.in/t3H4vCs"
},
{
id:10,
name:"👠 Footwear (Sandals, Heels, Sneakers)",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/sandal/s/h/l/-original-imahmgpdnuqnxmxv.jpeg?q=70",
link:"https://fktr.in/LhGvrTx"
},
{
id:11,
name:"💍 Jewellery",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jewellery-set/u/t/p/-original-imahft6rpx9zayhh.jpeg?q=70",
link:"https://fktr.in/kgf97qu"
},
{
id:12,
name:"⌚ Watches",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/watch/l/q/p/1-girl-watch-with-free-bracelet-timorix-women-original-imahcqhybrjbdh43.jpeg?q=70",
link:"https://fktr.in/ddenmra"
},
{
id:13,
name:"🕶️ Sunglasses",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/sunglass/e/u/q/m-oval-gbrown-hexagon-gblack-eyevy-original-imahgughwtkhpjgs.jpeg?q=70",
link:"https://fktr.in/Y5dvRh7"
},
{
id:14,
name:"🧣 Dupattas & Stoles",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/scarf/r/s/l/free-size-rn00861-riddle-needle-original-imahk67uuztz9esy.jpeg?q=70",
link:"https://fktr.in/k0CyJ7g"
},
{
id:15,
name:"💄 Beauty & Makeup",
category:"Beauty",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/makeup-kit/l/a/5/all-in-one-makeup-set5-toroka-original-imahzc6szgz9h9hg.jpeg?q=70",
link:"https://fktr.in/yvd0c3w"
},
{
id:16,
name:"🧴 Skincare",
category:"Beauty",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/moisturizer-cream/2/t/b/-original-imahzyn3nzegvaqp.jpeg?q=70",
link:"https://fktr.in/vx5UrB0"
},
{
id:17,
name:"💇 Hair Accessories",
category:"Beauty",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/hair-accessory/r/8/u/soft-fabric-hair-scrunchies-for-women-girls-hair-bands-combo-original-imahngwzangvqupx.jpeg?q=70",
link:"https://fktr.in/FoS1so6"
},
{
id:18,
name:"🛌 Nightwear",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/kzegk280/night-suit/v/u/k/xl-ske4001-black-pati-night-suit-trinabh-original-imagbfg7rwbkvyvm.jpeg?q=70",
link:"https://fktr.in/r40uQ7Z"
},
{
id:19,
name:"👙 Lingerie",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/lingerie-set/t/1/i/40b-padded-bra-panty-set-for-women-girls-bikini-original-imahad2pxzjbdb5m.jpeg?q=70",
link:"https://fktr.in/lfY8Pcr"
},
{
id:20,
name:"🧥 Winter Wear",
category:"Women's Fashion",
price:149,
oldPrice:499,
discount:"60% OFF",
rating:4.5,
delivery:"Free Delivery",
image:"https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/z/1/g/s-1-no-women-winter-jacket52-slc-original-imahhmyph8x75tku.jpeg?q=70",
link:"https://fktr.in/fVZIo7i"
},
{
  id: 21,
  name: "womans fashion all",
  category: "All",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/p/4/p/3xl-el-01white-goldbutti-aarti-fashion-resized-original-imahd4mnha5ysggu.jpeg?q=70",
  link: "https://fktr.in/C2OrAbx"
},
{
  id: 22,
  name: "T-Shirts",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/0/h/8/s-tsrt-moq2-kajaru-resized-original-imah8yzgyqvkyyfb.jpeg?q=70",
  link: "https://fktr.in/12bcBCI"
},
{
  id: 23,
  name: "Casual Shirts",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/f/l/v/l-vb-10-full-sh-fsn-original-imahpatf3kn4bcyg.jpeg?q=70",
  link: "https://fktr.in/zhdAhDV"
},
{
  id: 24,
  name: "Formal Shirts",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/k/g/k/l-sh4sg-pactimo-original-imahgnjhzezuy9fj.jpeg?q=70",
  link: "https://fktr.in/X4T4QDU"
},
{
  id: 25,
  name: "Polo T-Shirts",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/i/3/b/-resized-original-imahfxvfhubwp9uv.jpeg?q=70",
  link: "https://fktr.in/Y1cCq9M"
},
{
  id: 26,
  name: "Jeans",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/x/e/v/34-ajjeans-m-ajj-original-imahzy6bbsukwrqc.jpeg?q=70",
  link: "https://fktr.in/Jj4vtco"
},
{
  id: 26,
  name: "Trousers",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/trouser/u/i/w/34-a04-checktwill-trousers-pk2-gibbonte-resized-original-imah88pbhxeseynv.jpeg?q=70",
  link: "https://fktr.in/cnV2HnB"
},
{
  id: 27,
  name: "Cargo Pants",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/cargo/9/u/m/26-p-jogger-ten-pocket-dark-green-plus91-original-imahdnzyxpcbmgzf.jpeg?q=70",
  link: "https://fktr.in/8dZO2hx"
},
{
  id: 28,
  name: "Track Pants",
  category: "Men's Fashion",
  price: 227,
  oldPrice: 1599,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/e/p/z/xl-rex-track-pant-tigersnake-original-imahjtfgfy2fyhrp.jpeg?q=70",
  link: "https://fktr.in/Od2t3SF"
},
{
  id: 29,
  name: "Western Wear for Women",
  category: "Women's Fashion",
  price: 264,
  oldPrice: 999,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://images.meesho.com/images/products/481529598/teg2x_512.avif?width=360",
  link: "https://bitli.in/4Mm6Un8"
},
{
  id: 30,
  name: "Bottom Western Wear Women",
  category: "Women's Fashion",
  price: 264,
  oldPrice: 999,
  discount: "86% OFF",
  rating: 4.3,
  delivery: "Free Delivery",
  image: "https://images.meesho.com/images/products/295800910/awccr_512.avif?width=360",
  link: "https://bitli.in/aJmix0h"
}
];
